### ISSUE TITLE
A trouble encountered during the installation of logKcal

### ISSUE THREAD

**Issue by wangym9308** [jedick/logKcalc#1]
Hello, I am a beginner of R language user, and I have some trouble in installing the "logKcal" package through the Rstudio IDE. 

I do not have any trouble in installing the package of "CHNOSZ". However, I find I cannot successfully install the ''logKcal''

The error prompt is like the below: 
Error: Failed to install 'logKcalc' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 137-137 (vig5.Rmd) 
E> Error: processing vignette 'vig5.Rmd' failed with diagnostics:
E> species not available: As(OH)3()
E> --- failed re-building 'vig5.Rmd'
E> 
E> SUMMARY: processing the following files failed:
E>   'vig1.Rmd' 'vig2.Rmd' 'vig5.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted

If anybody can help me solve this problem, I will be greatly appreciated.

Thanks in advance!

**Comment by jedick** [comment]
Hi @wangym9308, thanks for opening the issue.

The problem is that some of the vignettes use code that assumes that As(OH)3 (an aqueous species) is in the OBIGT database in CHNOSZ. This species was added in the development version of CHNOSZ, and is not in earlier versions -- including the release version currently on CRAN (1.3.6).

With commit 9ea51f1 parameters of As(OH)3 are now added if needed for previous versions of CHNOSZ. Please try to install logKcalc again.

**Comment by wangym9308** [comment]
Hello Dr Dick,
Thanks so much for your answer and help. 
However, I find another problem here during my installation. I still do not know how to fix it.

_Error: Failed to install 'logKcalc' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> diagram: using maximum affinity method for 2-D diagram
E> balance: moles of SO4-2 in formation reactions
E> diagram: using maximum affinity method for 2-D diagram
E> --- finished re-building 'vig5.Rmd'
E> 
E> SUMMARY: processing the following files failed:
E>   'vig1.Rmd' 'vig2.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted

Besides, I find that I can install "logKcal" successfully by setting "build_vignettes = FALSE". Could you tell me what is the function of the vignettes here?

Thanks again!

**Comment by jedick** [comment]
Thanks for testing the installation again. The problem probably is that the gridExtra package is not available, which is used in vig1.Rmd and vig2.Rmd. Please try this revised command to install logKcalc:

`remotes::install_github("jedick/logKcalc", build_vignettes = TRUE, dependencies = TRUE)`

The `dependencies = TRUE` will install all the suggested packages, including gridExtra.

It's possible to install and use logKcalc without the vignettes. I would recommend building the vignettes because then you have the entire documentation for the version of the package that's on your computer.

**Comment by wangym9308** [comment]
Thanks Dr Dick. With your help, I have successfully installed the "logKcal" into my Rstudio. Your answers help me a lot. Have a good day!
